### ISSUE TITLE
stable installed applications fingerprint

### ISSUE THREAD

**Issue by Valve** [fingerprintjs/fingerprint-android#2]
It's easy to install/remove apps, which will lead to "installed apps" fingerprint change.
Is it possible to detect if an application is a system application (or a vendor-provided application) that cannot be removed?

This way we'll have a way to create a stable app list fingerprint (and keep the ability to see all apps fingerprint if necessary).

**Comment by Alexey-Verkhovsky** [comment]
Yes, it's possible. The set of system applications you mentioned is provided with a device firmware. I.e. the set is connected with the firmware. I don't think we will add entropy we already have with OS Build fingerprint.  On the other hand, several sources of truth can give an ability to detect spoofing of build info.

**Comment by Valve** [comment]
Thanks, closing for now, we'll reopen when we have more information from actual users.
