### ISSUE TITLE
SIGSEGV (signal SIGSEGV: invalid address (fault address: 0x0))

### ISSUE THREAD

**Issue by ergo-notch** [fingerprintjs/fingerprint-android#31]
The library returns me this error & crash the app: 
SIGSEGV (signal SIGSEGV: invalid address (fault address: 0x0))

![Captura de Pantalla 2021-05-28 a la(s) 14 53 57](https://user-images.githubusercontent.com/16563876/120035702-9d63f100-bfc4-11eb-90d0-a6606e81ca71.png)

**Comment by Alexey-Verkhovsky** [comment]
Hello! 
Can you provide following information about the bug? 
1. Device
2. Android version
3. Library version
4. Logcat output
5. Circumstances, steps to reproduce

**Comment by Alexey-Verkhovsky** [comment]
Hey, I assume this is related to [this bug](https://github.com/material-components/material-components-android/issues/2059) in the material-design library, which appeared in the version 1.3. It happens only in API levels lower than 21. For solving the problem decrease the material design library version to 1.2.1, or increase minAPI level to 21 (The latest release of fingerprint-android library has minAPI level 21)

If this doesn't help, please, reopen the issue and provide additional information listed above.

Thanks!
